"""
config.py — All configurable parameters for the forex trading bot.
"""


from datetime import timezone, timedelta


IB_HOST = "127.0.0.1"
IB_PORT = 4002
IB_CLIENT_ID = 1

SYMBOL   = "GBPUSD"
CURRENCY = "EUR"
ACCOUNT_CURRENCY = CURRENCY
SECTYPE  = "CASH"
EXCHANGE = "IDEALPRO"

TOTAL_CAPITAL = 100000.0
TRADE_QUANTITY = 0.2
SIZING_CACHE_MINUTES = 15
MIN_ORDER_QUANTITY   = 0

REF_TZ = timezone(timedelta(hours=8))
ASIA_LOCAL_OPEN_HOUR  = 9
ASIA_LOCAL_CLOSE_HOUR = 18
LONDON_LOCAL_OPEN_HOUR  = 8
LONDON_LOCAL_CLOSE_HOUR = 17
NY_LOCAL_OPEN_HOUR  = 8
NY_LOCAL_CLOSE_HOUR = 17

BAR_SIZE = "5 mins"

VALUE_AREA_PCT = 0.70
VP_BAR_SIZE    = "1 min"
VP_MIN_BARS    = 10

EMA_MAIN  = 100
EMA_TREND = 9
WARMUP_DURATION = "1 D"

MAX_SLOTS   = 10
RISK_REWARD = 2.75

STALE_TRIGGER_MAX_MINUTES = 10

STATE_FILE = "bot_state.json"
